language: python

python:
- "3.4"
- "3.5"
- "3.6"
- "3.7"

script:
- pip install flake8 pep8-naming
- flake8 --version
- flake8 --max-line-length=110 .
- git diff --check `git rev-list --max-parents=0 HEAD`
